module.exports = {
	profile: require('./profile'),
	faq: require('./faq'),
	register: require('./register'),
	post: require('./post'),
	gig: require('./gig'),
	user: require('./user'),
	comment: require('./comment'),
	tag: require('./tag'),
	locations: require('./locations'),
	auth: require('./auth'),
	image: require('./image'),
	people: require('./people'),
	message: require('./message'),
	event: require('./event'),
	connection: require('./connection'),
};
